### PR TITLE
Fix #12 - Error objects are not logged correclty

### LINKED ISSUE #12: Error objects are not logged correclty
Today, we use JSON.stringify to log Objects... This lead to the following result for errors:

```
var logger = require("node-tech-logger");
logger.error(new Error("error message"));

>> error: [module.js] {}
```

We should handle Error object differently and log error message and stack.

### PR DESCRIPTION
**Pull request by arenoux**

### CODE REVIEW

File: techLogger.js [hunk 1]
```diff
@@ -156,7 +156,9 @@ function _doLog(log) {
 function _log(level, log) {
 
     var message = log.map(function(element) {
-        if (typeof element !== "string") {
+        if (element instanceof Error) {
+            return element.stack;
```
Comment (sebz) [inline techLogger.js:160]: Just to be sure, the `element.stack` does not need to be stringified ?

Comment (arenoux) [inline techLogger.js:160]: I just checked with this test :

```
# var err = new Error("toto");
> undefined
# typeof err.stack 
> "string"
```

I'll check javascript doc :)

Comment (sebz) [inline techLogger.js:160]: It should be OK and moreover, the tests are OK, so LGTM :+1:
